name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install webapp
      run: git clone -b master https://github.com/blackbingo/digicom-open-suite-webapp.git digicom-open-suite-webapp
    - name: move to the right place
      run: mkdir -p digicom-open-suite-webapp/modules/axelor-open-suite && ls | grep -v digicom-open-suite-webapp | xargs -I{} mv {} digicom-open-suite-webapp/modules/axelor-open-suite
    - name: Grant execute permission for gradlew
      run: chmod +x digicom-open-suite-webapp/gradlew
    - name: Check spotless format with gradle task
      run: cd digicom-open-suite-webapp && ./gradlew spotlessCheck
    - name: Check changelog generation with gradle task
      run: cd digicom-open-suite-webapp && ./gradlew generateChangelog
    - name: Build without tests
      run: cd digicom-open-suite-webapp && ./gradlew -xtest clean build
    - name: Run tests
      run: cd digicom-open-suite-webapp && ./gradlew test
